/**
 * Type definitions for task hierarchy models
 *
 * @module core/models
 *
 * @remarks
 * Defines the four-level task hierarchy used throughout the PRP Pipeline:
 * Phase > Milestone > Task > Subtask. All types use readonly properties
 * to ensure immutability and prevent accidental state mutation.
 *
 * @example
 * ```typescript
 * import { Backlog, Status } from './core/models.js';
 *
 * const backlog: Backlog = {
 *   backlog: [
 *     {
 *       id: 'P1',
 *       type: 'Phase',
 *       title: 'Phase 1: Foundation',
 *       status: 'Planned',
 *       description: 'Project initialization',
 *       milestones: []
 *     }
 *   ]
 * };
 * ```
 */

/**
 * Lifecycle status of a work item in the PRP Pipeline
 *
 * @remarks
 * Each work item progresses through these states as it moves from
 * conception to completion. The Architect Agent creates items in
 * 'Planned' status, and the Task Orchestrator updates status as
 * work progresses.
 *
 * - `Planned`: Initial state after Architect Agent generates the backlog
 * - `Researching`: Research Agent is gathering context for PRP generation
 * - `Implementing`: Coder Agent is actively implementing the PRP
 * - `Complete`: All validation gates passed, work is done
 * - `Failed`: Implementation failed, requires retry or manual intervention
 * - `Obsolete`: Work item was deprecated or replaced (e.g., delta session)
 *
 * @example
 * ```typescript
 * import { Status } from './core/models.js';
 *
 * const currentStatus: Status = 'Implementing';
 * ```
 */
export type Status =
  | 'Planned'
  | 'Researching'
  | 'Implementing'
  | 'Complete'
  | 'Failed'
  | 'Obsolete';

/**
 * Type discriminator for the four levels of task hierarchy
 *
 * @remarks
 * Each work item has a `type` field that indicates its level in the
 * hierarchy. This enables type narrowing when processing heterogeneous
 * collections of work items.
 *
 * @example
 * ```typescript
 * import { ItemType } from './core/models.js';
 *
 * const type: ItemType = 'Subtask';
 * ```
 */
export type ItemType = 'Phase' | 'Milestone' | 'Task' | 'Subtask';

/**
 * Leaf node in the task hierarchy - the smallest unit of work
 *
 * @remarks
 * Subtasks represent atomic work items that can be completed in a single
 * implementation pass. Each subtask has a PRP (Product Requirement Prompt)
 * generated by the Researcher Agent and executed by the Coder Agent.
 *
 * The `context_scope` field contains critical instructions for the Coder Agent,
 * defining what code it can access and modify during implementation.
 *
 * @see {@link https://github.com/anthropics/claude-code/blob/main/PRP-TEMPLATE.md | PRP Template}
 *
 * @example
 * ```typescript
 * import { Subtask, Status } from './core/models.js';
 *
 * const subtask: Subtask = {
 *   id: 'P1.M1.T1.S1',
 *   type: 'Subtask',
 *   title: 'Create TypeScript interfaces for task hierarchy',
 *   status: 'Planned',
 *   story_points: 2,
 *   dependencies: [],
 *   context_scope: 'Strict scope: src/core/ directory only'
 * };
 * ```
 */
export interface Subtask {
  /**
   * Unique identifier following dot-notation hierarchy
   *
   * @format P{phase}.M{milestone}.T{task}.S{subtask}
   * @example 'P1.M1.T1.S1'
   */
  readonly id: string;

  /** Type discriminator for type narrowing */
  readonly type: 'Subtask';

  /**
   * Human-readable title of the work item
   *
   * @minLength 1
   * @maxLength 200
   */
  readonly title: string;

  /** Current lifecycle status */
  readonly status: Status;

  /**
   * Estimated complexity in Fibonacci story points
   *
   * @remarks
   * Uses the Fibonacci sequence: 1, 2, 3, 5, 8, 13, 21
   * Larger values indicate higher uncertainty and complexity
   *
   * @min 1
   * @max 21
   */
  readonly story_points: number;

  /**
   * IDs of subtasks that must complete before this one can start
   *
   * @remarks
   * The Task Orchestrator uses this array to enforce dependency ordering.
   * Empty array means no dependencies.
   *
   * @example ['P1.M1.T1.S1', 'P1.M1.T1.S2']
   */
  readonly dependencies: string[];

  /**
   * Strict instructions for isolated development
   *
   * @remarks
   * Defines INPUT (what to use), OUTPUT (what to produce), and MOCKING
   * (what external services to fake). This context is injected into the
   * Coder Agent's prompt.
   *
   * @example
   * ```
   * INPUT: TaskRegistry from dependency P1.M2.T1.S1
   * OUTPUT: TaskService.create() method
   * MOCKING: Groundswell agents, file system operations
   * ```
   */
  readonly context_scope: string;
}

/**
 * Container for related subtasks forming a coherent unit of work
 *
 * @remarks
 * Tasks represent intermediate-level work items that group related subtasks.
 * A Task is typically completed when all its subtasks are Complete.
 *
 * @example
 * ```typescript
 * import { Task, Status } from './core/models.js';
 *
 * const task: Task = {
 *   id: 'P1.M1.T1',
 *   type: 'Task',
 *   title: 'Initialize TypeScript Project',
 *   status: 'Planned',
 *   description: 'Set up package.json, tsconfig.json, and directory structure',
 *   subtasks: [
 *     {
 *       id: 'P1.M1.T1.S1',
 *       type: 'Subtask',
 *       title: 'Initialize package.json',
 *       status: 'Complete',
 *       story_points: 1,
 *       dependencies: [],
 *       context_scope: '...'
 *     }
 *   ]
 * };
 * ```
 */
export interface Task {
  /**
   * Unique identifier following dot-notation hierarchy
   *
   * @format P{phase}.M{milestone}.T{task}
   * @example 'P1.M1.T1'
   */
  readonly id: string;

  /** Type discriminator for type narrowing */
  readonly type: 'Task';

  /** Human-readable title of the work item */
  readonly title: string;

  /** Current lifecycle status */
  readonly status: Status;

  /**
   * Detailed description of the task's objectives
   *
   * @remarks
   * Explains what the task accomplishes and how its subtasks
   * contribute to the overall goal.
   */
  readonly description: string;

  /**
   * Array of subtasks that comprise this task
   *
   * @remarks
   * Tasks contain subtasks, forming a parent-child relationship.
   * The Task Orchestrator processes subtasks sequentially based on
   * dependency ordering within this array.
   */
  readonly subtasks: Subtask[];
}

/**
 * Significant checkpoint or deliverable within a phase
 *
 * @remarks
 * Milestones represent major progress points that group related tasks.
 * They often correspond to deliverable increments or validation gates.
 *
 * @example
 * ```typescript
 * import { Milestone, Status } from './core/models.js';
 *
 * const milestone: Milestone = {
 *   id: 'P1.M1',
 *   type: 'Milestone',
 *   title: 'Project Initialization',
 *   status: 'Complete',
 *   description: 'Foundation setup and environment configuration',
 *   tasks: []
 * };
 * ```
 */
export interface Milestone {
  /**
   * Unique identifier following dot-notation hierarchy
   *
   * @format P{phase}.M{milestone}
   * @example 'P1.M1'
   */
  readonly id: string;

  /** Type discriminator for type narrowing */
  readonly type: 'Milestone';

  /** Human-readable title of the work item */
  readonly title: string;

  /** Current lifecycle status */
  readonly status: Status;

  /**
   * Detailed description of the milestone's objectives
   *
   * @remarks
   * Explains what the milestone accomplishes and what deliverables
   * are expected upon completion.
   */
  readonly description: string;

  /**
   * Array of tasks that comprise this milestone
   *
   * @remarks
   * Milestones contain tasks, forming a parent-child relationship.
   * Tasks are processed based on their internal dependencies.
   */
  readonly tasks: Task[];
}

/**
 * Top-level container representing a major development phase
 *
 * @remarks
 * Phases represent the highest level of organization in the PRP Pipeline.
 * Each phase typically corresponds to a major capability or milestone
 * in the overall product roadmap (e.g., "Foundation", "Core Agent System").
 *
 * @example
 * ```typescript
 * import { Phase, Status } from './core/models.js';
 *
 * const phase: Phase = {
 *   id: 'P1',
 *   type: 'Phase',
 *   title: 'Phase 1: Foundation & Environment Setup',
 *   status: 'Complete',
 *   description: 'Project initialization, environment configuration, and core data structures',
 *   milestones: []
 * };
 * ```
 */
export interface Phase {
  /**
   * Unique identifier for the phase
   *
   * @format P{phase}
   * @example 'P1'
   */
  readonly id: string;

  /** Type discriminator for type narrowing */
  readonly type: 'Phase';

  /** Human-readable title of the work item */
  readonly title: string;

  /** Current lifecycle status */
  readonly status: Status;

  /**
   * Detailed description of the phase's objectives
   *
   * @remarks
   * Explains the overall goals, scope, and expected outcomes
   * for this phase of development.
   */
  readonly description: string;

  /**
   * Array of milestones that comprise this phase
   *
   * @remarks
   * Phases contain milestones, forming the top level of the hierarchy.
   * The PRP Pipeline processes phases sequentially.
   */
  readonly milestones: Milestone[];
}

/**
 * Root container for the entire task backlog
 *
 * @remarks
 * The Backlog interface represents the top-level structure stored in
 * `tasks.json`. It contains an array of Phases, forming the complete
 * hierarchy of work for the PRP Pipeline.
 *
 * The Session Manager loads this structure, and the Task Orchestrator
 * iterates through it to execute work items.
 *
 * @see {@link ./architecture/system_context.md#task-hierarchy-json-schema | System Context}
 *
 * @example
 * ```typescript
 * import { Backlog, Phase } from './core/models.js';
 *
 * const backlog: Backlog = {
 *   backlog: [
 *     {
 *       id: 'P1',
 *       type: 'Phase',
 *       title: 'Phase 1: Foundation',
 *       status: 'Planned',
 *       description: 'Project setup and core data structures',
 *       milestones: []
 *     },
 *     {
 *       id: 'P2',
 *       type: 'Phase',
 *       title: 'Phase 2: Core Agent System',
 *       status: 'Planned',
 *       description: 'Groundswell agent integration and prompt system',
 *       milestones: []
 *     }
 *   ]
 * };
 * ```
 */
export interface Backlog {
  /**
   * Array of phases comprising the complete project backlog
   *
   * @remarks
   * This is the root of the task hierarchy. All phases, milestones,
   * tasks, and subtasks are contained within this array.
   *
   * The Task Orchestrator processes phases sequentially in order,
   * then recursively processes nested items.
   */
  readonly backlog: Phase[];
}
